-- Dropbox-ODI-Demo · Snowflake setup
-- ----------------------------------------------------------------------
-- Provisions:
--   - Warehouse:  ODI_WH
--   - Database:   ODI_DROPBOX
--     Schemas:    BRONZE, SILVER, GOLD
--   - Roles:      FIVETRAN_LOADER (write to BRONZE), DBT_BUILDER (rw all)
--   - User:       FIVETRAN_USER (assigned FIVETRAN_LOADER)
-- ----------------------------------------------------------------------
-- Run as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ODI_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Dropbox-ODI-Demo: Fivetran loads + dbt builds';

CREATE DATABASE IF NOT EXISTS ODI_DROPBOX
  COMMENT = 'Dropbox-ODI-Demo medallion lake';

CREATE SCHEMA IF NOT EXISTS ODI_DROPBOX.BRONZE
  COMMENT = 'Fivetran landing zone — one table per Dropbox file + _FILES metadata';
CREATE SCHEMA IF NOT EXISTS ODI_DROPBOX.SILVER
  COMMENT = 'dbt labs (bronze→silver): conformed staging + intermediate';
CREATE SCHEMA IF NOT EXISTS ODI_DROPBOX.GOLD
  COMMENT = 'dbt labs (silver→gold): marts + semantic layer';

-- Roles --------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS FIVETRAN_LOADER
  COMMENT = 'Used by the Dropbox custom connector';
CREATE ROLE IF NOT EXISTS DBT_BUILDER
  COMMENT = 'Used by dbt to build silver + gold';

GRANT USAGE ON WAREHOUSE ODI_WH TO ROLE FIVETRAN_LOADER;
GRANT USAGE ON WAREHOUSE ODI_WH TO ROLE DBT_BUILDER;

GRANT USAGE ON DATABASE ODI_DROPBOX TO ROLE FIVETRAN_LOADER;
GRANT USAGE ON DATABASE ODI_DROPBOX TO ROLE DBT_BUILDER;

-- Fivetran writes only to BRONZE
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE PIPE,
      CREATE STREAM, CREATE TASK, CREATE FILE FORMAT
  ON SCHEMA ODI_DROPBOX.BRONZE TO ROLE FIVETRAN_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA ODI_DROPBOX.BRONZE TO ROLE FIVETRAN_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA ODI_DROPBOX.BRONZE TO ROLE FIVETRAN_LOADER;

-- dbt reads BRONZE, writes SILVER and GOLD
GRANT USAGE ON SCHEMA ODI_DROPBOX.BRONZE TO ROLE DBT_BUILDER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ODI_DROPBOX.BRONZE TO ROLE DBT_BUILDER;
GRANT SELECT ON ALL TABLES IN SCHEMA ODI_DROPBOX.BRONZE TO ROLE DBT_BUILDER;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW,
      CREATE DYNAMIC TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA ODI_DROPBOX.SILVER TO ROLE DBT_BUILDER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW,
      CREATE DYNAMIC TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA ODI_DROPBOX.GOLD TO ROLE DBT_BUILDER;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA ODI_DROPBOX.SILVER TO ROLE DBT_BUILDER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA ODI_DROPBOX.GOLD TO ROLE DBT_BUILDER;

-- Service user (rotate the password before production use) ------------------
CREATE USER IF NOT EXISTS FIVETRAN_USER
  PASSWORD = 'CHANGE_ME_BEFORE_FIRST_RUN'
  DEFAULT_ROLE = FIVETRAN_LOADER
  DEFAULT_WAREHOUSE = ODI_WH
  DEFAULT_NAMESPACE = ODI_DROPBOX.BRONZE
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Dropbox-ODI-Demo Fivetran service user';
GRANT ROLE FIVETRAN_LOADER TO USER FIVETRAN_USER;

-- Hand DBT_BUILDER out to whoever runs dbt (sysadmin example) ---------------
GRANT ROLE DBT_BUILDER TO ROLE SYSADMIN;
GRANT ROLE FIVETRAN_LOADER TO ROLE SYSADMIN;

-- Smoke check ---------------------------------------------------------------
SHOW SCHEMAS IN DATABASE ODI_DROPBOX;
